# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForkSweeper < Formula
  desc "Remove unused GitHub forks"
  homepage "https://github.com/rednafi/fork-sweeper"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.2/fork-sweeper_Darwin_arm64.tar.gz"
      sha256 "0d113b20bb8e66353729454ec46482ce60aa2bdde89e0fc71a11dabc60c051b0"

      def install
        bin.install "fork-sweeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.2/fork-sweeper_Darwin_x86_64.tar.gz"
      sha256 "7543673fbe45c147769639c81fee7f0c92146dd05df60bcc18e39c672258f9f0"

      def install
        bin.install "fork-sweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.2/fork-sweeper_Linux_x86_64.tar.gz"
      sha256 "c7afde40810d80d9a267a77d091c3c6279b346a632b4ed0307aa517a4140eb70"

      def install
        bin.install "fork-sweeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.2/fork-sweeper_Linux_arm64.tar.gz"
      sha256 "934edd28af374f0e185376c955788dc350433511d5b346faab29ca4f7f7e4e7a"

      def install
        bin.install "fork-sweeper"
      end
    end
  end
end
