# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkPatrol < Formula
  desc "Remove unused GitHub forks"
  homepage "https://github.com/rednafi/fork-sweeper"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.0/fork-sweeper_Darwin_arm64.tar.gz"
      sha256 "38dcac68ed1f95adf8ff30fb7a28ab0e42f97ea31a7661fef33b1fe660ac86a1"

      def install
        bin.install "fork-sweeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.0/fork-sweeper_Darwin_x86_64.tar.gz"
      sha256 "e5c40d14a8c181ab4dbc08dc366e674de9cac223b062e0f2fffbc28f05fa7dff"

      def install
        bin.install "fork-sweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.0/fork-sweeper_Linux_arm64.tar.gz"
      sha256 "84f19956dc56939881c683d9cb7266767ee5d33d1779be2118a6371ad415a9fb"

      def install
        bin.install "fork-sweeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/fork-sweeper/releases/download/v0.1.0/fork-sweeper_Linux_x86_64.tar.gz"
      sha256 "b2c7e45ced44572c6f7780f930007a270baf083f455e77b51e1b3228648c7079"

      def install
        bin.install "fork-sweeper"
      end
    end
  end
end
