name: test
on:
  push:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Install dependencies
        run: make init

      - name: Lint
        run: make lint-check

      - name: check-is-dirty
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Detected uncommitted changes."
            git status
            git diff
            exit 1
          fi

      - name: Run tests
        run: make test
